
// Products
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';
export const RECEIVE_ORDER_PRODUCTS = 'RECEIVE_ORDER_PRODUCTS';
