
// Products
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT';
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS';
export const RECEIVE_ORDER = 'RECEIVE_ORDER';
export const RECEIVE_ORDER_PRODUCTS = 'RECEIVE_ORDER_PRODUCTS';
export const CREATE_NEW_ORDER = 'CREATE_NEW_ORDER';
export const CREATE_NEW_ORDERPRODUCT = 'CREATE_NEW_ORDER_PRODUCT';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY'
export const SET_CART = 'SET_CART';
export const SET_VIEWED_USER = 'SET_VIEWED_USER';
export const DELETE_USER = 'DELETE_USER';
export const RECEIVE_REVIEWS = 'RECEIVE_REVIEWS';
